language: node_js
node_js:
  - 'lts/*'
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  # caching temporarily disabled, see https://github.com/cypress-io/cypress/issues/4595
  npm: false
  ## directories:
    # we also need to cache folder with Cypress binary
    ## - ~/.cache
    ## - /home/travis/.cache/Cypress

install:
  - npm install -g npm-install-peers

before_script:
  - npm install
  - npm-install-peers

script:
  - npm test
  - codecov